In [2]:
import pandas as pd

df = pd.read_csv("../data/data.csv", encoding="ISO-8859-1")

print("Dataset Shape:")
print(df.shape)

df.head()

Dataset Shape:
(541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [4]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [5]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
# Remove rows where CustomerID is missing
df = df.dropna(subset=['CustomerID'])

print("After removing missing CustomerID:")
print(df.shape)

After removing missing CustomerID:
(406829, 8)

In [7]:
# Remove cancelled orders
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

print("After removing cancelled orders:")
print(df.shape)

After removing cancelled orders:
(397924, 8)

In [8]:
# Convert InvoiceDate to datetime format
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  object
 1   StockCode    397924 non-null  object
 2   Description  397924 non-null  object
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[ns]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  float64
 7   Country      397924 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.3+ MB

In [9]:
# Create Sales column

df['Sales'] = df['Quantity'] * df['UnitPrice']

df[['Quantity','UnitPrice','Sales']].head()

   Quantity  UnitPrice  Sales
0         6       2.55  15.30
1         6       3.39  20.34
2         8       2.75  22.00
3         6       3.39  20.34
4         6       3.39  20.34

# Data Cleaning Summary

## Steps Performed

1. Loaded the dataset
2. Inspected data structure
3. Checked missing values
4. Removed rows with missing CustomerID
5. Removed cancelled transactions
6. Converted InvoiceDate to datetime format
7. Created Sales column

## Dataset Used

Online Retail Dataset

## Objective

Prepare clean transaction data for Cohort Retention Analysis and Customer Lifetime Value (CLTV) calculations.

In [10]:
# Create Invoice Month

df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')

df[['InvoiceDate', 'InvoiceMonth']].head()

          InvoiceDate InvoiceMonth
0 2010-12-01 08:26:00      2010-12
1 2010-12-01 08:26:00      2010-12
2 2010-12-01 08:26:00      2010-12
3 2010-12-01 08:26:00      2010-12
4 2010-12-01 08:26:00      2010-12

In [11]:
# Find first purchase month for each customer

cohort_data = df.groupby('CustomerID')['InvoiceMonth'].min().reset_index()

cohort_data.columns = ['CustomerID', 'CohortMonth']

cohort_data.head()

   CustomerID CohortMonth
0     12346.0     2011-01
1     12347.0     2010-12
2     12348.0     2010-12
3     12349.0     2011-11
4     12350.0     2011-02

In [ ]:
# Merge cohort month into main dataframe

df = df.merge(cohort_data, on='CustomerID')

df[['CustomerID', 'InvoiceMonth', 'CohortMonth']].head()

   CustomerID InvoiceMonth CohortMonth
0     17850.0      2010-12     2010-12
1     17850.0      2010-12     2010-12
2     17850.0      2010-12     2010-12
3     17850.0      2010-12     2010-12
4     17850.0      2010-12     2010-12